scripts/run_attack_args_helper.py, textattack/transformations/__init__.py, textattack/transformations/word_swap.py, textattack/transformations/word_swap_homoglyph.py, textattack/transformations/word_swap_neighboring_character_swap.py, textattack/transformations/word_swap_random_character_deletion.py, textattack/transformations/word_swap_random_character_insertion.py, textattack/transformations/word_swap_random_character_substitution.py, textattack/transformations/word_swap_wordnet.py
transformation using synonyms derived from [WordNet](https://wordnet.princeton.edu/) via NLTK
--
I tried using WordNet as a drop-in replacement for the counterfitted nearest-neighbors substitution of textfooler. I attacked BERT on the MR dataset.
**original textfooler results**
```
┌───────────────────────────────┬────────┐
│ Attack Results                │        │
├───────────────────────────────┼────────┤
│ Number of successful attacks: │ 846    │
│ Number of failed attacks:     │ 5      │
│ Number of skipped attacks:    │ 149    │
│ Original accuracy:            │ 85.1%  │
│ Accuracy under attack:        │ 0.5%   │
│ Attack success rate:          │ 99.41% │
│ Average perturbed word %:     │ 14.74% │
│ Average num. words per input: │ 19.06  │
│ Avg num queries:              │ 140.76 │ …
```
=> Wordnet transformation

README.md, local_tests/python_function_tests.py, textattack/__init__.py, textattack/augmentation/__init__.py, textattack/augmentation/augmenter.py, textattack/augmentation/recipes.py, textattack/constraints/semantics/word_embedding_distance.py
I want to allow multiple word swaps in the augmented examples but I'm waiting until the search space PR gets merged to add that.
=> augmentation in TextAttack

textattack/constraints/semantics/word_embedding_distance.py, textattack/datasets/dataset.py, textattack/shared/scripts/mturk_prep/se_thresh/gather_csv.py, textattack/shared/scripts/run_attack_parallel.py, textattack/shared/utils.py, textattack/shared/word_embedding.py
When using Pytorch `multiprocessing` to share Tensors between processes, there's a pretty well documented [issue](https://github.com/pytorch/pytorch/issues/973) where file descriptors don't get closed properly, so when we hit file descriptor limit, our code breaks. This also happens with TextAttack, so I changed sharing strategy from `file_descriptor` to `file_system`. Also, changed some `open` expressions so that they're used within `with` (this wasn't the cause of the issue however).
=> Fix for file descriptor leak bug

.gitignore, textattack/goal_function_results/goal_function_result.py, textattack/loggers/file_logger.py, textattack/loggers/visdom_logger.py, textattack/loggers/weights_and_biases_logger.py, textattack/search_methods/attack.py, textattack/shared/__init__.py, textattack/shared/checkpoint.py, textattack/shared/scripts/run_attack_args_helper.py, textattack/shared/scripts/run_attack_parallel.py, textattack/shared/scripts/run_attack_single_threaded.py
Add checkpoint feature so that users can save intermediate results when running attacks that take a long time on a large number of samples. This way, if process crashes for some reason, users can recover their results and continue to run the attack.
Added three command line arguments
- `--checkpoint-resume`: this takes the name of the checkpoint file (`*.ta.chkpt`) that users want to recover from. If set to "latest",  TextAttack automatically chooses latest saved checkpoint from checkpoint directory
- `--checkpoint-dir`: path of the checkpoint directory. This is where TextAttack will save checkpoint files and search for the files when loading. Default is set to `TextAttack/checkpoints`.
- `--checkpoint-interval`: the number of attacks TextAttack should process before saving checkpoint. …
=> Add checkpoint feature for running long attacks

textattack/shared/scripts/run_attack_parallel.py
I forgot to set default `num_examples_offset` and `num_examples` in non-resume case in parallel script.
=> fix parallel script

textattack/transformations/word_swap_wordnet.py
It's possible `l.name()` is actually same word as  `word`, in which case it's not a perturbation
It's also possible that `l.name()` actually suggests phrases joined by '_' or hyphenated compound words. Since most of them introduce new meaning, choose to ignore them.
=> fix non-change swaps

textattack/shared/checkpoint.py, textattack/shared/scripts/run_attack_args_helper.py, textattack/shared/scripts/run_attack_parallel.py, textattack/shared/scripts/run_attack_single_threaded.py
Yet another bug for recovering from checkpoint when running parallel script. I mistakenly applied the same recovery logic for single thread version to the parallel version. But in parallel version, `num_examples` should be the original num of examples (e.g. 1000) instead of remaining attacks because of the `while` loop condition.
This probably raises a point that we need tests for checkpoint.
=> fix recovery logic

textattack/tokenizers/auto_tokenizer.py
Fast Tokenizer is back again! Last time, I disabled it because `TokenizerFast` could not be pickled for multiprocessing. Not only is that issue now [fixed](https://github.com/huggingface/tokenizers/issues/87), but we don't even need to pickle it anymore since we clear tokenizer from `TokenizedText` to save memory in our worker process before sharing it with the main process (not sure why I didn't think of that before)
This should give us around 20~30% speed up.
=> add fast tokenizer

textattack/commands/attack/attack_args.py, textattack/commands/attack/attack_args_helpers.py, textattack/commands/attack/attack_command.py, textattack/constraints/pre_transformation/__init__.py, textattack/constraints/pre_transformation/max_word_index_modification.py
Having the `choices` keyword argument in parser prevents us from having command line args with arguments like `word-swap-embedding:max_candidates=20`.
=> remove choices from parser

textattack/search_methods/genetic_algorithm.py
I forgot some edge cases for genetic algorithm, like when for crossover, both parents are not perturbed. In that case, `last_transformation` doesn't exist in either of the parents' `attacked_text.attack_attrs`.
Also, simplify low probability assignment b/c whatever I had before actual make no sense and hurts when there are only a few transformations available. For example, if `num_zero_elements` is close to 100, then epsilon is big and we end up assigning way too high probability.
=> add fix for genetic

Makefile, requirements.txt, setup.py, tests/test_command_line/test_attack.py, tests/test_command_line/test_augment.py, tests/test_command_line/test_list.py, tests/test_misc.py, textattack/augmentation/recipes.py, textattack/constraints/grammaticality/language_models/google_language_model/google_language_model.py, textattack/constraints/grammaticality/language_models/learning_to_write/rnn_model.py, textattack/constraints/grammaticality/part_of_speech.py, textattack/constraints/semantics/sentence_encoders/infer_sent/infer_sent_model.py, textattack/models/helpers/glove_embedding_layer.py, textattack/models/helpers/lstm_for_classification.py, textattack/models/helpers/word_cnn_for_classification.py
- fix flair version bug and fix version; 
- fix isort version bug and fix verison;
- fix alzantot abstract constraint class bug
=> minor bug fixes

textattack/commands/attack/attack_command.py
Without the patch, I get the error below
```
textattack: First time running textattack: downloading remaining required packages.
textattack: Downloading NLTK required packages.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Unzipping taggers/universal_tagset.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
2020-07-06 14:57:00.111904: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened …
```
=> Make sure seed is integer

textattack/augmentation/augmenter.py, textattack/augmentation/recipes.py, textattack/commands/attack/attack_args_helpers.py, textattack/commands/train_model/run_training.py, textattack/commands/train_model/train_args_helpers.py, textattack/commands/train_model/train_model_command.py, textattack/shared/validators.py
Based on `textattack train --attack *recipe*`, TextAttack will run an attack against the current model at the beginning of each new training epoch, and use the resulting adversarial examples as training data for that epoch. This should improve robustness. Benchmarks coming soon.
Also allows for a combination of data augmentation and adversarial training (and fixes augmentation of eval set bug)
=> augmentation updates, adversarial training

textattack/commands/attack/run_attack_parallel.py, textattack/constraints/grammaticality/language_models/learning_to_write/language_model_helpers.py, textattack/goal_functions/goal_function.py, textattack/shared/attack.py
- bigger model & constraint cache sizes
- RNN doesn't try to predict in the [quite rare] case that it receives an empty tensor as input
- attacking w `--parallel` can handle dataset out-of-bounds errors
=> fix fast-alzantot recipe

textattack/goal_functions/goal_function.py, textattack/models/helpers/lstm_for_classification.py, textattack/transformations/word_swap_gradient_based.py
Deals with issue #209, where the switch to a gradient free embedding layer was causing problems for white box transforms like word_swap_gradient_based
=> Patch lstm hotflip

textattack/commands/train_model/run_training.py, textattack/commands/train_model/train_model_command.py, textattack/transformations/word_swap_gradient_based.py
quick change to the training code I was using to get the adversarial training results for the paper. `textattack train --save-last` saves the model weights to disk after the last epoch, instead of only preserving the highest eval acc. When adversarial training you're often more interested in the robustness of the model after a specific number of epochs, not in getting the highest possible eval acc
.
=> --save-last option for training

textattack/transformations/word_swap_masked_lm.py
the bug was in this line: `word_tokens = self._lm_tokenizer.tokenize(current_text.words[index])`
was returning a list like `['worse', '[PAD]', '[PAD]', '[PAD]', '[PAD]', ... '[PAD]', '[PAD]', '[PAD]', '[PAD]']` -- of length 256. so the subword replacement was trying 256^48 = 3.9e115 combinations before choosing the top-K. obviously, this was an infinite loop (also amazing that it worked at all -- bc python generators I guess)
anyways, replaced the `self._lm_tokenizer.tokenize` with `self._lm_tokenizer.encode(current_text.words[index], add_special_tokens=False)`, which doesn't include pad tokens. the attack works now and is actually (relatively) fast.
=> fix BERT-attack tokenization bug

textattack/commands/attack/run_attack_parallel.py, textattack/commands/attack/run_attack_single_threaded.py, textattack/commands/train_model/run_training.py, textattack/commands/train_model/train_args_helpers.py, textattack/commands/train_model/train_model_command.py, textattack/goal_functions/goal_function.py, textattack/shared/utils/misc.py
- attacking: fix tensorflow memory growth & gpu specification: now `--parallel` works with every recipe (including `textfooler`, `bae`, etc.)
- training: add `--check-robustness` option for running attacks each epoch and logging metrics [but not adversarial training]
- training: log to pytorch native tensorboard instead of `tensorboardX`
=> parallel fix; add --check-robustness training option

docs/datasets_models/Example_0_tensorflow.ipynb, docs/datasets_models/Example_1_sklearn.ipynb, docs/datasets_models/Example_2_allennlp.ipynb, docs/examples/0_End_to_End.ipynb, docs/examples/1_Introduction_and_Transformations.ipynb, docs/examples/2_Constraints.ipynb
This pull request addresses an issue where the 'Run in Colab' buttons not rendered on readthedocs #244.
The cause of this issue is that [nbsphinx does not currently support HTML-style hyperlinks](https://github.com/spatialaudio/nbsphinx/issues/468).
This pull request changes the HTML-style hyperlinks used for the 'Run in Colab' and 'View Source in GitHub' buttons with Markdown image links. Screenshots of what that looks like are attached below.
***
The docs build correctly after running `make html`. I didn't run any of the other tests, as this change just affects the `docs/` folder.
I think I got all of the ipynb files in `docs/`. Let 
***
**Screenshot of how it looks on jupyter notebook:**
**Screenshot of how it looks from the browser:**
=> Replace HTML hyperlinks with Markdown image hyperlinks in ipynb docs

textattack/shared/attack.py
If constraint cache size is too small, it's possible that some of the early hits would be evicted by new entries by `filter_transformation_uncached`.
=> fix faulty cache misses

.github/workflows/make-docs.yml
Our documentation checks are broken because of this known error, an incompatibility issue between jupyter and ipython-console. Annoying. Luckily, this is a known thing, and we can fix it by simply downgrading ipython: https://github.com/jupyter/notebook/issues/4050
=> sphinx ipykernel workaround

requirements.txt
- transformers: 3.0.2 --> 3.3.0
- tokenizers: 1.0.8-rc1 --> 1.0.8-rc2
- numpy: 1.19.2 --> something below 1.19 (because that's what tensorflow 2.0 requires)
=> update package versions

tests/sample_outputs/run_attack_targetedclassification2_wordnet_langtool_log-to-csv_beamsearch2_attack_n.txt, textattack/constraints/grammaticality/part_of_speech.py, textattack/shared/attacked_text.py
Flair's tokenizer sometimes causes issues with POS tagging since it doesn't tokenize a sentence into words like TextAttack does. For example, if we have the word "KO'ed", Flair will tokenize it as "KO'", "ed", but TextAttack treats "KO'ed" as one word. So when we perform POS tagging, we won't find "KO'ed" in the word list returned by Flair.
Flair allows users to specify their own tokenizer as a function that takes in a string and returns a list of tokens. `textattack.shared.utils.words_from_text` does this exactly.
=> have flair use textattack tokenization method

docs/api/constraint.rst, tests/sample_outputs/run_attack_cnn_cola.txt, tests/sample_outputs/run_attack_stanza_pos_tagger.txt, tests/test_command_line/test_attack.py, textattack/commands/attack/attack_args.py, textattack/constraints/grammaticality/__init__.py, textattack/constraints/grammaticality/cola.py, textattack/shared/utils/install.py
- Add a constraint to check that the attacked text is deemed grammatically acceptable by a model pre-trained on the CoLA dataset
- I'm not convinced that `COLA` is the best name for this constraint, but I couldn't come up with anything else. Suggestions are welcome. 
- The `run_attack_targeted_mnli_misc` test is failing on my local machine with  "Avg num queries: 182.0" rather than the new 181.0 value. I was unable to determine the issue since none of my changes should have affected this test.
=> Add a CoLA based constraint

tests/test_misc.py, textattack/augmentation/__init__.py, textattack/augmentation/augmenter.py, textattack/commands/augment.py
The augmenter we have right now only supports single word swaps, making many transformations inapplicable for augmentation purposes. 
The complicity here is due to the parameter `pct_words_to_swap `, which allows users to set the maximum number of words to swap during augmentation. We have to call transformation as many times as we can, but the max number of words swapped can not exceed the allowance set by user. What I changed here is to use the length of `AttackedText.attack_attrs["modified_indices"]` to count the number of swapped words, instead of the previous method of using a list of random indices to perform single word swap. In this way, we could perform any transformation, see if it fits the constraints/allowance, then decide to whether return the augmentation or continue …
=> New augmenter

docs/1start/basic-Intro.rst
The previous link https://github.com/QData/TextAttack/blob/master/docs/quickstart/installation.rst doesn't work anymore.
=> Installation link fix

textattack/transformations/word_swap_change_name.py
This fix accounts for sentences with just the firstname, or the lastname in them. 
`S-PER` NER was not accounted for in the transformation.
=> Transformation Fix: WordSwapNameChange

textattack/shared/utils/strings.py
As per https://github.com/QData/TextAttack/issues/325#issuecomment-723136430, some custom embeddings contain words with "_@*" in the vocabulary, it'd be helpful to take this into consideration when tokenizing attacked sentences
=> Allow words connected by additional special char

textattack/goal_functions/goal_function.py, textattack/shared/validators.py
I was trying to build an attack with a modified goal function, but I was unable to because of the errors raised in the `validate_model_goal_function_compatibility` function in textattack/shared/validators.py. I think these logger warnings will make it easier for people to experiment with custom goal functions.
=> turn unknown goal function error into a logger warning

textattack/transformations/word_swap_inflections.py
I think `textattack/transformations/word_swap_inflections.py` had a couple issues. [These are issues in the sense that the Morpheus attack&ndash;that relies on this transformation&ndash;is not a correct copy of the authors' original implementation of Morpheus when it uses this transformation.]
Specifically:
**1.** The function `_get_replacement_words` wasn't returning the correct lists of inflections. For example, notice that
```
>>> lemminflect.getAllLemmas('is')
{'AUX': ('be',), 'VERB': ('be',)}
```
However, according to the Morpheus paper, we want not only 'be', but 'been', 'am', 'was', 'are', 'were', and 'being'. To get this full list, you must take one of the lemmas returned by `lemminflect.getAllLemmas` (in this case, 'be') and get its inflections: 
```
>>> …
```
=> fix inflection generation and enlarge pos to upos mapping (for Morpheus)

tests/sample_outputs/run_attack_faster_alzantot_recipe.txt, textattack/search_methods/genetic_algorithm.py, textattack/search_methods/greedy_word_swap_wir.py, textattack/search_methods/search_method.py, textattack/shared/attack.py
It seems that when none of the items in `results` have a higher score than the `cur_result.score`, the `num_queries` attribute of `cur_result` exits the while loop in the `_perform_search` method with an incorrect value of model queries. I think this fixes the problem.
=> fix model query count when no candidate result scores are improvements over current result score

README.md, README_ZH.md, markdowntable_test.md
Thanks for releasing the powerful TextAttack🎉
For chinese fellows easier to get started with TextAttack, I translate the reademe to chinese. I try my best to adheres to `信、达、雅`,  the translation principles.  But only the content is guaranteed to be informative. This chinese version may need some major review. Despite all this, it's still a good startpoint.
Look forward to receiving your reply~
=> Add chinese version of readme

.github/workflows/run-pytest.yml, requirements.txt, setup.py, tests/sample_outputs/interactive_mode.txt, tests/sample_outputs/kuleshov_cnn_sst_2.txt, tests/sample_outputs/run_attack_faster_alzantot_recipe.txt, tests/sample_outputs/run_attack_flair_pos_tagger_bert_score.txt, tests/sample_outputs/run_attack_gradient_greedy_word_wir.txt, tests/sample_outputs/run_attack_hotflip_lstm_mr_4.txt, tests/sample_outputs/run_attack_stanza_pos_tagger.txt, tests/test_word_embedding.py, textattack/attack_recipes/kuleshov_2017.py, textattack/augmentation/recipes.py, textattack/constraints/semantics/sentence_encoders/thought_vector.py, textattack/constraints/semantics/word_embedding_distance.py, textattack/shared/__init__.py, textattack/shared/utils/misc.py, textattack/shared/utils/strings.py, textattack/shared/word_embedding.py, textattack/transformations/word_swap_embedding.py
1. extended the WordEmbedding class to implement 2 ways to initialize a word embedding: one is as before downloading from s3 all the files needed(embeddingmat, cos_sim_mat, etc..); the other being using gensim keyedvector to avoid re-implementing things(example in test case) 
2. incorporated WordEmbeddings with WordSwapEmbedding and WordEmbeddingDistance and ThoughtVector as per https://github.com/QData/TextAttack/issues/325#issuecomment-724888184. APIs of these 3 class are unchanged except an additional argument in __init__ to indicate whether to use embeddings from textattack s3 or in gensim keyedvectors format.
=> custom embeddings

textattack/attack_recipes/clare_li_2020.py, textattack/attack_recipes/textbugger_li_2018.py
This PR fixes some of the parameter settings for TextBugger and CLARE recipe. For TextBugger, it fixes the issue raised by #363.
=> update recipe parameters

textattack/transformations/word_swaps/word_swap_hownet.py
WordSwapHowNet originally used to brown corpus tag set, but we recently switched to universal tag set. This PR reflects the change and fixes issue reported in #374
=> fix tag type used by WordSwapHowNet

textattack/models/wrappers/model_wrapper.py
This fixes issue #365 and #354 by not requiring `get_grad` to be defined by child class of `ModelWrapper`
=> make get_grad normal method

README.md, tests/sample_outputs/list_augmentation_recipes.txt, textattack/augmentation/__init__.py, textattack/augmentation/recipes.py, textattack/commands/augment.py
This is the augmentation recipe from CLARE, which uses the following transformations:
- WordSwapMaskedLM
- WordInsertionMaskedLM
- WordMergeMaskedLM
The default model and tokenizer are both `distilroberta-base`. Specific models/tokenizers can be specified by the user if they decide to call `CLAREAugmenter` in python.
=> Clare augmentation recipe

textattack/commands/train_model/run_training.py
As Adversarial training using training data, although here has a random sample, it's more reasonable to use eval data to check robustness.
=> Change check_robustness dataset

textattack/transformations/word_insertions/word_insertion_masked_lm.py, textattack/transformations/word_merges/word_merge_masked_lm.py, textattack/transformations/word_swaps/word_swap_masked_lm.py
In `WordSwapMaskedLM`, `WordInsertionMaskedLM`, `WordMergeMasedLM`, we use `torch.argsort` to pick the tokens that have the highest probability. However, `torch.argsort` sorts in ascending order by default, so we need to pass `descending=True` to reverse sort it. Also, it fixes a bug where we replace the words with tokens that have not been sanitized (i.e. you may see "##" appear). 
- Pass `descending=True` to `torch.argsort` in `WordSwapMaskedLM`, `WordInsertionMaskedLM`, `WordMergeMasedLM`.
- Sanitize top tokens before adding them to candidate set.
=> Fix Bug in Masked LM Transformations

tests/test_word_embedding.py, textattack/shared/word_embedding.py
* This PR adds the possibility to use FastText embeddings for the WordSwapEmbedding augmentation by passing the KeyedVectors (Word2Vec or FastText) to the `__init__` of GensimWordEmbeddings.
- Support for FastText word vectors in GensimWordEmbedding class (not only Word2Vec)
- GensimWordEmbeddings `__init__` now requires passing pre-loaded WordEmbeddingsKeyedVectors
- GensimWordEmbeddings `__init__` does not support passing the path of a saved word embedding file anymore (due to specific loading logic of different embedding types)
- [ X ] The title of your pull request should be a summary of its contribution.
- [ X ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  ] If your …
=> Added support for FastText word vectors in GensimWordEmbedding class

textattack/shared/word_embedding.py
This PR fixes issue [#424](https://github.com/QData/TextAttack/issues/424) by replacing "\\" with "/" on the path join command.
=> Quick fix for issue #424

textattack/goal_functions/classification/untargeted_classification.py
=> UntargetedClassification: Don't check self.target_max_score when it is already known to be None

textattack/augmentation/augmenter.py, textattack/augmentation/recipes.py
Addresses pytest issues of https://github.com/QData/TextAttack/pull/368
Here are #368 descriptions
**Problem**
When using `EasyDataAugmenter`, there are two cases that will cause the augmenter to run into an infinite loop. 
Case 1: Text that contains duplicated words e.g. `hello hello hello`
For a sentence / phrase containing duplicated words (`hello hello`), `RandomSwap` would not be able to successfully perform the swap since both words are the same. This causes `words_swapped` to never reach 0 and hence the while loop will never reach its break condition. 
Case 2: Text that contains words with no synonym e.g. `hey derek`
For a sentence / phrase e.g. `hey derek` where there is no synonym that can be inserted, `RandomSynonymInsertion` would not be able to successfully insert a synonym …
=> fix pr 368 to pass pytest

docs/1start/FAQ.md, textattack/loggers/attack_log_manager.py, textattack/shared/attacked_text.py
fix terrible match algorithm in `all_words_diff`. See this for detail #451 .. some of the issue text is copied for easier reference
**Describe the bug**
**To Reproduce**
Run following command `textattack attack --model cnn-ag-news --recipe textbugger --num-examples 10`
**Expected behavior**
As shown in the pic, the real `Average perturbed word %` should not reach that high. I found the reason in `attack_recipes/shared/attacked_text.py:line 234`.
```python
def all_words_diff(self, other_attacked_text):
"""Returns the set of indices for which this and other_attacked_text
have different words."""
indices = set()
w1 = self.words
w2 = other_attacked_text.words
for i in range(min(len(w1), len(w2))):
if w1[i] != w2[i]:
indices.add(i)
return indices
```
Apparently this comparison according to the …
=> fix all_words_diff problem

requirements.txt
Update Pytorch version requirement to be above 1.7.0 but skip 1.8.0
Previously, we had to limit Pytorch to 1.7.1 b/c 1.8.0 broke backward compatability for LSTM models. This has been fixed in 1.9.0, so we can just skip 1.8 versions.
- Change Pytorch version to be above 1.7.0 but skip 1.8.0
-
=> Update torch version requirement

README.md, README_ZH.md, docs/1start/FAQ.md, docs/3recipes/augmenter_recipes.rst, docs/3recipes/augmenter_recipes_cmd.md, examples/train/train_albert_snli_entailment.sh, examples/train/train_bert_stsb_similarity.sh, examples/train/train_lstm_rotten_tomatoes_sentiment_classification.sh, textattack/models/wrappers/huggingface_model_wrapper.py, textattack/models/wrappers/pytorch_model_wrapper.py
* Fix all textattack train commands regarding the recent rework updates..*
- textattack train --model * change to "textattack train --model-name-or-path "
- multiple other args names also changed when "textattack train "
- remove all the following mentions, because not sure if still supported..
```bash
textattack train --model lstm --dataset rotten_tomatoes --augment eda --pct-words-to-swap .1 --transformations-per-example 4
```
- [  ] If your pull request addresses an issue, please mention the issue number in the pull request description to make …
=> document fix regarding the new training commands 

docs/conf.py, docs/requirements.txt, textattack/attack.py, textattack/attack_args.py, textattack/attacker.py, textattack/augment_args.py, textattack/dataset_args.py, textattack/model_args.py, textattack/trainer.py, textattack/training_args.py
* api-rework added multiple modules in the textattack root level. however all are missing docstring; these made the readthedoc API reference missing these modules*
- *added docstrings at the beginning of each new module added by api-rework  in the textattack root level*
- [  ] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify the appropriate `.rst` …
=> adding the missed docstrings for api-rework-modules

README.md, textattack/attack_args.py, textattack/attack_recipes/__init__.py, textattack/attack_recipes/a2t_yoo_2021.py
Adds A2T and A2T-MLM attack from paper https://arxiv.org/abs/2109.00544. 
Added `a2t` recipe as `textattack.attack_recipes.A2TYoo2021`.
=> Add new attack recipe A2T

textattack/commands/eval_model_command.py
Fix a bug when running `textattack eval` with `--num-examples=-1` in CLI.
When running `textattack eval --num-examples=-1 ...`, it should be treated as `num_examples = len(dataset)` and evaluate the entire dataset. However, the code does not handle this case, the main loop is never executed, and it returns `preds=[]`.
- Add value check for `num_examples` before executing the main evaluation loop.
=> Fix a bug when running textattack eval with --num-examples=-1

docs/0_get_started/installation.md
Update installation.md to add FAQ on installation regarding issue #530
Update installation.md to add FAQ on installation
- revise installation.md to add FAQ on installation tips
=> Update installation.md to add FAQ on installation

textattack/dataset_args.py
In  [dataset_args.py](https://github.com/QData/TextAttack/blob/master/textattack/dataset_args.py), the function `_create_dataset_from_args()` tries to substitute the second element of `dataset_args`(a tuple) with user input from command line. This gives an error since elements of a tuple cannot be changed.
- NA
Create a new tuple with substituted value for the second element of `dataset_args`
- NA
- *[x] The title of your pull request should be a summary of its contribution.
- *[x] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- *[x] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people …
=> Fix dataset-split bug

textattack/transformations/word_insertions/word_insertion_masked_lm.py, textattack/transformations/word_merges/word_merge_masked_lm.py, textattack/transformations/word_swaps/word_swap_masked_lm.py
When the CLAREAugmenter substitutes a word, there's an extra character that is added to the front (Ġ). The CLARE transformation method should remove that extra character before the transformed text is returned by the transformation.
- Before a sentence is transformed, strip the substituting words of `Ġ` so that it doesn't appear in transformation.
- *[x] The title of your pull request should be a summary of its contribution.
- *[x] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- *[x] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the issue know you   are working on it)
- …
=> Fix CLARE Extra Character Bug

setup.py, tests/test_augment_api.py, textattack/transformations/sentence_transformations/back_translation.py
Added API docstrings for back translation.
Also provides a temporary fix to pytest caused by a known issue from tensorflow.
the issue can be seen here
https://github.com/huggingface/transformers/issues/14265
https://github.com/huggingface/transformers/issues/14266
to solve the issue tensorflow 2.5.0 is installed instead of 2.6.0
Also added test for back translation.
=> Add API docstrings for back translation

textattack/constraints/grammaticality/part_of_speech.py
This change fixes "AttributeError: module 'textattack' has no attribute 'shared'" as shown by issue 536 here: https://github.com/QData/TextAttack/issues/536
Before this PR, users were running into the problem of "AttributeError: module 'textattack' has no attribute 'shared'" whenever they were running the part_of_speech.py file. This PR uses the same logic from https://github.com/QData/TextAttack/pull/551 which solves the problem of the attribute not belonging to the module using a direct import of the module.
- The line "from textattack.shared.utils import LazyLoader, device" has been added.
- Changed "flair.device = textattack.shared.utils.device" to be "flair.device = device"
- Changed "stanza = textattack.shared.utils.LazyLoader("stanza", globals(), "stanza")" to be "stanza = …
=> Fixed the "no attribute" error from #536

textattack/attack_args.py, textattack/loggers/attack_log_manager.py, textattack/loggers/weights_and_biases_logger.py
- **Problems**: Current WandB integration in TextAttack only allows users to specify which project to log to (through the `--log_to_wandb` argument). This limits users from WandB's features such as grouping runs, adding notes, etc. Consequently, it's hard to organize the attack results as the number of experiments increases.
- **Proposed solution**: I suggest we should change the `log_to_wandb` from `str` type to `dict` type so the users can specify whatever arguments that `wandb.init()` accepts through this argument.
- Change `log_to_wandb` from `str` to `dict` type.
- Fix a bug in `textattack/loggers/attack_log_manager.py`: [This](https://github.com/QData/TextAttack/blob/bfc3468205e1217bd338bbad73f74b21d4c1c1d6/textattack/attack_args.py#L423) will throw an error since the …
=> Add flexibility to Wandb logger

textattack/transformations/word_insertions/word_insertion_masked_lm.py, textattack/transformations/word_merges/word_merge_masked_lm.py, textattack/transformations/word_swaps/word_swap_masked_lm.py
This PR is created to fix #589, in which the sentence encoder raises StopIteration when the `newly_modified_indices` of the attacked text is an empty set. This happens when the new words swapped/inserted/merged by the CLARE transformations do not contain any letters. Our current implementation keeps tracks of `newly_modified_indices` only when the new words at the modified indices are actually words, not symbols. An example is shown below:
Suppose we have the sentence 
> lovingly photographed in the manner of a golden book sprung to life , stuart little 2 manages sweetness largely without stickiness.
and apply [WordMergeMaskedLM](https://github.com/QData/TextAttack/blob/master/textattack/transformations/word_merges/word_merge_masked_lm.py) to the sentence, one of the transformations it …
=> Fix CLARE StopIteration Bug

textattack/commands/augment_command.py
Fixes the bug in the Augmenter Command class where extra quotation marks are added to the output csv files. This PR avoids using any changes to the input file or having to create a temporary file
Instead of changing how the csv reader works, an easier solution is to mark where quotes and commas occur within the text field while the data is being read into the DictReader(). Then before augmenting, commas and quotes are replaced back into the text value. This avoids the repeated quotation issue and the glitch where the first two quotes are removed by the csv reader. After the augmentation process, the output file is altered to remove any additional markings from the preprocessing.
=> Fixed quotation issues

textattack/constraints/semantics/sentence_encoders/thought_vector.py, textattack/constraints/semantics/word_embedding_distance.py, textattack/transformations/word_swaps/word_swap_embedding.py
By only instanciating the `counterfitted_GLOVE_embedding` when
necessary, the ram usage decreases by at least two gigabytes and the startup time decreases massively.
- `WordSwapEmbedding`, `WordEmbeddingDistance` and `ThoughtVector` only initialize `WordEmbedding.counterfitted_GLOVE_embedding`  upon initialization, not upon python parsing the files containing the class definitions. Initializing `counterfitted_GLOVE_embedding` means
- downloading large chunks of data on initial use
- loading a lot of data into ram, no matter whether it is ever used. …
=> Only initialize counterfitted_GLOVE_embedding when needed, massively decreasing ram usage

Makefile, requirements.txt
Fix black dependency issue. Package `pycld2` requires `black` 20.8b1, which does not work with the latest version of `click`. The version of `click` cannot exceed 8.1.0.
=> Fix black issue

tests/test_attacked_text.py, textattack/shared/utils/strings.py
This PR re-implements the functions `has_letter` and `words_from_text` in `textattack.shared.utils.strings.py` using Python's built-in regular expression module `re`.
NA
- Implementation of `has_letter` and `words_from_text` in `textattack.shared.utils.strings.py` now uses methods including `re.search`, `re.findall`, etc. from Python's built-in regular expression module `re`, in place of `str`'s methods `isalpha`, `isalnum`.
NA
- [  ] The title of your pull request should be a summary of its contribution.
- [  ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  ] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure …
=> enhance functions words_from_text and has_letter in strings.py using regular expression

textattack/loggers/weights_and_biases_logger.py
*PR fixes 2 issues seen when logging attack results to wandb*
*Logging Attack Results Summary to wandb is currently failing with TypeError - Data row contained incompatible types. Fix involves converting string entries to float(Number) to maintain same datatype throughout the column in the table.*
*As per the documentation , we do not have not specify project name to allow wandb create a project name automatically. Removed Assertion*
- *Added Code to convert string values in Attack Results Summary to Float for logging to wandb.*
- *Changed method to get project_name for wandb logging* 
- *Deleted Assertion which is not necessary*
**Issues Addressed 
- Fixes #646 
- Fixes #645 
- [  ] All public methods must have informative …
=> Fix logging to wandb in attack args for attackresults

textattack/models/wrappers/pytorch_model_wrapper.py
PR fixes gradient calculation for WordCNN  in `get_grad` function in `textattack/models/wrappers/pytorch_model_wrapper.py` .
*get_grad function currently calculates gradients irrespective of the inputs to the model. In models for which the inputs are not
transposed , the gradient is calculated incorrectly leading to errors in functions such as gradient_based word importance ranking used in A2T recipe.*
*get_grad changed to correctly calculate grad with appropriate tensor shape with respective to gradient genereated by the auto differentiation hook*
- *Changed `get_grad` function in `pytorch_model_wrapper.py` to include checks for Models with non-transposed inputs*
- Fixes #601
=> Fix WordCNN input embedding gradient calculation

textattack/search_methods/greedy_word_swap_wir.py
*While using query-budget constraints with pwws attacks, we get an IndexError. This is due to the `search_over` flag not being updated appropriately in the `weighted-saliency` condition block in the `_get_index_order` function.*
*PR updates `search_over` flag appropriately and added code to exit loop when `search_over` is set to True*
- *`search_over` flag appropriately updated and used to break out of loop to avoid unnecessary get_goal_results function calls.*
Fixes #437  
=> Fix Querybudget related IndexError in PWWS Attack

textattack/dataset_args.py
*In PR #533 , the third element of dataset_args needed to be set to args.dataset_split , but due to minor error the second element was being set as args.dataset_split instead.*
*This code change lead to bug described in Issue #599. *
*Commit includes appropriate fix to update the third element correctly.*
Change code from
```
dataset_args = (
dataset_args[:1] + (args.dataset_split,) + dataset_args[2:]
)
```
to 
```
dataset_args = (
dataset_args[:2] + (args.dataset_split,) + dataset_args[3:]
)
```
Fixes #599
=> Update dataset_args to correctly set dataset_split

textattack/trainer.py
*As detailed in Issue #498 , the adversarial dataset generated in `_generate_adversarial_examples` function in `trainer.py` was leading to the column indicating the example-type being masked/lost.*
*Due to the masking of the column all the examples were considered as clean_examples which is not expected behaviour.*
*Commit includes changes to the data-structure of `adversarial_examples` to suit the Dataset wrapper and changes to the condition statements in `collate_fn` function in `get_train_dataloader` function.*
- *adversarial_examples data structure was changed to suit Dataset Wrapper from `textattack.datasets.Dataset`.*
- *adversarial_examples data structure was initially `(tuple_containing(text) , label , "adversarial_example")`  which has been changed to `(tuple_containing(text , …
=> Fix adversarial dataset generation in trainer.py

textattack/shared/utils/strings.py
This PR adds more colors to the `color_from_output` function so that we can properly print and colorize in the terminal even with a large number of classes. Before, this worked in HTML but broke when trying to colorize label colors like "yellow" in ANSI.
=> add full range of ANSI colors for printing >3 classes

tests/sample_outputs/run_attack_deepwordbug_lstm_mr_2.txt, tests/sample_outputs/run_attack_flair_pos_tagger_bert_score.txt, tests/sample_outputs/run_attack_transformers_datasets.txt, tests/sample_outputs/run_attack_transformers_datasets_adv_metrics.txt, textattack/attack.py, textattack/search_methods/greedy_word_swap_wir.py, textattack/transformations/transformation.py
* `GreedyWordSwapWIR` calculates word importance by performing leave one out checks for all words in the input. It currently does not check if the word has modification constraints on them leading to unnecessary queries.*
* `GreedyWordSwapWIR` can be optimized by finding indices of words which can be modified and performing information ranking on these words only.*
*Optimization Suggested by @tsinggggg  in #294 *
- *Added new function `get_indices_to_order` in `attack.py` *
- *Changed GreedyWordSwapWIR `get_index_order` function for optimization*
- *Added new attribute to  `__call__` in class ` Transformation` to return modifiable_indices.*
Fixes #294 
- [  ] All public methods must have …
=> [WIP]Optimize GreedyWordSwapWIR with pretransformation constraints

textattack/transformations/sentence_transformations/back_translation.py
The example in the docstring of the [`BackTranslation`](https://textattack.readthedocs.io/en/latest/apidoc/textattack.transformations.sentence_transformations.html?highlight=backtranslation#backtranslation-class) example appears to have a typo: the `transformation` is given as `BackTranslation` (a _reference_ to the class) but should be `BackTranslation()` (an _instance_ of the class).
- N/A
- Correct example in docstring of `BackTranslation` class to correctly instantiate `BackTranslation()` as the `transformation`
- N/A
=> Fix typo in example of BackTranslation class docstring

textattack/loggers/csv_logger.py
*Using Dataframe Append method is deprecated by pandas and is not
considered good practice. Using Append method raises FutureWarning
which floods the stdout for every append call.*
*Commit uses Dataframe from_records function to achieve the same df and
creation of csv file from dataframe.*
- *Now using  a list to store all the row dictionaries and creating the dataframe using `pd.DataFrame.from_records` function.*
Fixes #668
=> Fix FutureWarning caused by pandas append method

textattack/search_methods/greedy_word_swap_wir.py
*There is a corner-case when `saliency_scores`  length is not equal to `len_text` , 
this happens when the query budget limits calculations of `leave_one_results`.*
- Moved `search_over` check to the start of the loop . 
- Changed `delta_ps` update when search_over = True. 
Fixes Issue raised by @pratyushmaini in #654
=> Handle when saliency_scores not equal to len_text

textattack/transformations/word_swaps/word_swap_change_number.py
Improve exception handling.
- I was running `CheckList` attack on `bert-base-uncased-ag-news` and caught an exception.
```bash
dang@local:~$ textattack attack --recipe checklist --model bert-base-uncased-ag-news --num-examples 1000 --random-seed 42 --log-to-csv log.csv --disable-stdout --shuffle
[Succeeded / Failed / Skipped / Total] 10 / 431 / 20 / 461:  46%|████▌     | 461/1000 [02:57<03:27,  2.60it/s]
Traceback (most recent call last):
File "/root/miniconda3/envs/tattack/bin/textattack", line 8, in <module>
sys.exit(main())
File "/root/miniconda3/envs/tattack/lib/python3.8/site-packages/textattack/commands/textattack_cli.py", line 50, in main
func.run(args)
File "/root/miniconda3/envs/tattack/lib/python3.8/site-packages/textattack/commands/attack_command.py", line 36, in run …
```
=> Improve exception handling for WordSwapChangeNumber

docs/conf.py, requirements.txt, setup.py, textattack/constraints/semantics/sentence_encoders/universal_sentence_encoder/multilingual_universal_sentence_encoder.py, textattack/models/tokenizers/glove_tokenizer.py, textattack/shared/utils/tensor.py, textattack/shared/word_embeddings.py
[in progress] updating libraries. datasets 2.4, transformers 4.2, gensim 4
=> [Draft] Updating transformers, datasets, gensim

textattack/shared/attacked_text.py
Lines 404 and 474 of the code store the same parameters, so delete line 474. 
If two identical parameters are saved at the same time, a long list of "prev_attacked_text" needs to be maintained internally when call `get_transformations` multiple times to generate `transformed_texts`. ` __eq__` function in `AttackedText` class is called repeatedly each time whether the `transformed_texts` exists in `constraints_cache`, and `__eq__` function compares all parameters item by item. If comparing "prev_attacked_text" with "previous_ attacked_text" will enter the linked list saved by each other, sometimes the layers are very deep, the code can get stuck for a long time comparing them, eventually the code will not continue to run normally.
- delete code line 474 …
=> Fix a issue may caused by attacked_text.py

textattack/shared/attacked_text.py, textattack/shared/utils/strings.py
=> Add typing to AttackedText class

textattack/constraints/semantics/bert_score.py, textattack/metrics/__init__.py, textattack/metrics/quality_metrics/__init__.py, textattack/metrics/quality_metrics/bert_score.py, textattack/metrics/quality_metrics/meteor_score.py, textattack/metrics/quality_metrics/sentence_bert.py
Add extra quality metrics: BERTScore, Sentence BERT and Meteor.
A better default model has been setted for BERTScore (as described in this [sheet](https://docs.google.com/spreadsheets/d/1RKOVpselB98Nnh_EOC4A2BYn8_201tmPODpNWu4w7xI/edit#gid=0))
How to use them?
```
attack_results = attacker.attack_dataset()
sbert_stats = SBERTMetric().calculate(attack_results)
bert_score_stats = BERTScoreMetric().calculate(attack_results)
meteor_stats = MeteorMetric().calculate(attack_results)
```
=> Extra quality metrics

textattack/attack_args.py
This change fixes the bug where "--model-batch-size" doesn't function when "--attack-recipe" argument is present.
This change fixes the bug where "--model-batch-size" doesn't function when "--attack-recipe" argument is present.
- *Example: Added a line to set `goal_function.batch_size` to `model_batch_size` argument. 
None. 
- [  ] The title of your pull request should be a summary of its contribution.
- [  ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  ] To indicate a work …
=> Fixed a batch_size bug in attack_args.py

docs/2notebook/1_Introduction_and_Transformations.ipynb, docs/2notebook/2_Constraints.ipynb, docs/2notebook/4_Custom_Datasets_Word_Embedding.ipynb, tests/test_command_line/test_attack.py
Comment out the stanza attack test 
- [  ] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify the …
=> Stanza test and notebooks minor fix

.github/workflows/run-pytest.yml
The "Test with PyTest" GitHub action is failing inconsistently. On my local machine, all tests pass, but when run through [GitHub actions](https://github.com/QData/TextAttack/actions/runs/6425242361/job/17931194310), the operation fails with the below message:
```
tests/test_command_line/test_train.py::test_train_tiny 
Error: The operation was canceled.
```
When I profile this test on my local machine, it consumes over 8GB of memory, which is more than the default Ubuntu runner has. As such, I believe the test is flaky due to running out of memory. This PR addresses this by adding an additional 8GB to the swap file. 
- Increased the swap file size for the GitHub actions runner by 8GB 
- N/A
- N/A
- [ X  ] The title of your pull request should be a summary of its contribution.
- [ X ] …
=> Increase the swap file size of the GitHub actions runner

tests/test_transformations.py, textattack/transformations/word_swaps/word_swap_change_location.py, textattack/transformations/word_swaps/word_swap_change_name.py
This PR adds a new `consistent` parameter to `WordSwapChangeLocation` and `WordSwapChangeName` so that all original instances of the same word get updated to the same new word. This allows for consistency when the semantics of the words matter. For example,  "Alice likes Bob. Alice does not like Eve." could be transformed into "Kate likes Bob. Kate does not like Eve" if `consistent = True`. Otherwise, the text could be transformed into "Alice likes Bob. Kate does not like Eve." which alters the semantics of the sentence. 
- Added `consistent` parameter to `WordSwapChangeLocation` and `WordSwapChangeName`. 
- `WordSwapChangeLocation` has been updated to only make one modification to the original text for marginal  performance gains. 
- `WordSwapChangeLocation` has been updated to correctly …
=> Consistent word swap

docs/0_get_started/installation.md
This PR fixes a couple minor typos at https://textattack.readthedocs.io/en/master/0_get_started/installation.html.
N/A
Typos have been corrected.
N/A
=> Typo corrections in installation docs

README.md, README_ZH.md, docs/1start/attacks4Components.md, docs/1start/what_is_an_adversarial_attack.md, textattack/attack_recipes/genetic_algorithm_alzantot_2018.py
This fixes the typos when referring to `faster-alzantot` as `fast-alzantot` (probably some leftovers from #463 )
- References to `faster-alzantot` in documentation, READMEs and docstrings have been fixed to refer to the correct recipe name
=> Fix faster-alzantot recipe references

docs/apidoc/textattack.constraints.semantics.sentence_encoders.rst, docs/apidoc/textattack.constraints.semantics.sentence_encoders.sentence_bert.rst, textattack/attack_args.py, textattack/attack_recipes/a2t_yoo_2021.py, textattack/constraints/semantics/sentence_encoders/__init__.py, textattack/constraints/semantics/sentence_encoders/bert/__init__.py, textattack/constraints/semantics/sentence_encoders/sentence_bert/__init__.py, textattack/constraints/semantics/sentence_encoders/sentence_bert/sbert.py, textattack/metrics/quality_metrics/sentence_bert.py
This PR adds renames the BERT constraint, which is a sentence-level constraint using BERT, to SBERT to better reflect its functionality.
- Rename `BERT` constraint to `SBERT`.
- N/A
- N/A
- [ X ] The title of your pull request should be a summary of its contribution.
- [ X ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [ X ] Make sure existing tests pass.
- [  ] Add relevant tests. No quality testing = …
=> Rename BERT constraint to SBERT

textattack/transformations/word_swaps/word_swap_qwerty.py
This PR fixes an IndexError in WordSwapQWERTY when random_one is True and the word contains non-qwerty characters.
This PR is related to #717 
- Check if the adjacent_char list is empty before calling random.choice
=> Word Swap Qwerty Failure Bug Fix

README.md, docs/3recipes/augmenter_recipes_cmd.md, docs/apidoc/textattack.transformations.sentence_transformations.rst, tests/test_augment_api.py, textattack/augment_args.py, textattack/augmentation/recipes.py, textattack/transformations/sentence_transformations/__init__.py, textattack/transformations/sentence_transformations/back_transcription.py
This PR adds [back transcription](https://aclanthology.org/2023.emnlp-main.724) data augmentation method, which uses TTS+ASR pipeline
- Added `BackTranscription` transformation as `textattack.transformations.sentence_transformations.BackTranscription`.
- Added `back_transcription` built-in recipe for data augmentation.
- Added back transcription test as `test_back_transcription`.
- None
- None
=> Add back transcription augmentation method

textattack/augmentation/recipes.py
This PR resolves a bug where using the EDA augmentation recipe would not work with the textattack augmentation cli. This issue was because the EDA recipe did not accept the default arguments defined in the Augmentation superclass. This change resolves this issue by accepting a var-keyword parameter, which is then passed to the component Augmenter objects used by the EDA recipe.
This PR resolved the bug raised in #796, which found that running the EDA recipe from the textattack augmentation cli would raise a ``TypeError: __init__() got an unexpected keyword argument `high_yield` ``
- Changes EDA recipe to accept a var-keyword parameter, which is passed to the component Augmenter objects
=> Fix bug where EDA augmentation recipe would not accept default Augmentation arguments
