.gitignore
local_tests/command_line_tests.py
requirements.txt
textattack/goal_function_results/goal_function_result.py
textattack/loggers/__init__.py
textattack/loggers/attack_log_manager.py
textattack/loggers/file_logger.py
textattack/loggers/logger.py
textattack/loggers/visdom_logger.py
textattack/loggers/weights_and_biases_logger.py
textattack/shared/scripts/run_attack_args_helper.py
textattack/shared/scripts/run_attack_parallel.py
textattack/shared/scripts/run_attack_single_threaded.py
textattack/shared/utils.py

- rename `AttackLogger` to `AttackLogManager`
- some other minor renames
- add Weights & Biases logging

Logging updates; add Weights & Biases

---

MANIFEST.in
README.md
requirements.txt
setup.py
textattack/config.json
textattack/shared/utils.py

- read cache dir from `os.environ.TA_CACHE_DIR`
- move config.yaml to aws by default; allow user to change it
- add post-install hook so users don't have to run all those commands
- make logger nice

minor fixes to install + logging

---

textattack/shared/checkpoint.py
textattack/shared/scripts/run_attack_args_helper.py
textattack/shared/scripts/run_attack_parallel.py

Missed changing arguments for checkpoint.

fix bug with checkpoint for parallel

---

textattack/attack_results/attack_result.py
textattack/loggers/weights_and_biases_logger.py
textattack/search_methods/genetic_algorithm.py
textattack/shared/checkpoint.py
textattack/shared/scripts/run_attack_parallel.py
textattack/shared/tokenized_text.py

hopefully last issue with running checkpoint recovery for parallel script.

reduce TokenizedText memory usage

---

textattack/shared/scripts/run_attack_args_helper.py
textattack/shared/tokenized_text.py

- add white-box transformations to attack_args_helper
- a tiny bit of type validation for TT
[tests pass]

white-box transformations from command-line

---

setup.py
textattack/__main__.py

`textattack` is now a shortcut for `python -m textattack`

add 'textattack' as standalone command

---

CONTRIBUTING.md
README.md
requirements.txt
setup.py
textattack/commands/attack/attack_args_helpers.py
textattack/commands/attack/attack_command.py
textattack/goal_functions/classification/untargeted_classification.py
textattack/goal_functions/goal_function.py
textattack/loggers/attack_log_manager.py
textattack/shared/attack.py
textattack/shared/utils/install.py
textattack/shared/utils/misc.py
textattack/shared/utils/tensor.py

- get rid of `config.yaml`
- tensorflow hub, transformers, etc. use TA_CACHE_DIR
- add `pip install "[.dev]"` option

universal cache dir

---

README.md
textattack/goal_functions/goal_function.py
textattack/shared/attack.py

Update get_goal_results signature

---

README.md
docs/examples/1_Introduction_and_Transformations.ipynb
requirements.txt
tests/sample_inputs/sst_model_and_dataset.py
tests/sample_outputs/interactive_mode.txt
tests/test_command_line/test_attack.py
textattack/commands/attack/attack_args.py
textattack/commands/attack/attack_args_helpers.py
textattack/commands/eval_model/eval_model_command.py
textattack/commands/list_things.py
textattack/commands/train_model/train_args_helpers.py
textattack/datasets/__init__.py
textattack/datasets/huggingface_nlp_dataset.py
textattack/datasets/translation/ted_multi.py
textattack/models/README.md
textattack/models/helpers/utils.py

- fix a couple documentation bugs
- upload Di's models: MR {CNN, LSTM}, Yelp {CNN, LSTM}, SST LSTM
- add models/README.md with info about models
- update eval script to support regression

models updates

---

README.md
docs/quickstart/command_line_usage.md
examples/augmentation/augment.csv
examples/augmentation/augment.sh
textattack/augmentation/augmenter.py
textattack/augmentation/recipes.py
textattack/commands/augment.py
textattack/commands/train_model/run_training.py
textattack/commands/train_model/train_args_helpers.py
textattack/commands/train_model/train_model_command.py
textattack/transformations/word_deletion.py
textattack/transformations/word_swap_random_word.py

Combine training and data augmentation in one command using `textattack train --augment`

train --augment

---

tests/test_command_line/test_attack.py
textattack/attack_results/attack_result.py
textattack/commands/attack/attack_args_helpers.py

- and set `shuffle=True` default

better word matching when printing in color

---

tests/sample_outputs/interactive_mode.txt
textattack/attack_recipes/textfooler_jin_2019.py
textattack/search_methods/greedy_word_swap_wir.py

depends on #212
changes TextFooler wir method from `unk` to `del`

textfooler recipe fix

---

docs/examples/1_Introduction_and_Transformations.ipynb
docs/examples/2_Constraints.ipynb

Updating 2 of the tutorial notebooks to work with changes to how we handle models, datasets, and attacking. Also add an example of attacking custom samples as requested in #218.
Closes #218

Update notebooks to work with changes

---

textattack/constraints/grammaticality/language_models/google_language_model/alzantot_goog_lm.py
textattack/constraints/grammaticality/part_of_speech.py
textattack/constraints/semantics/sentence_encoders/thought_vector.py
textattack/goal_functions/goal_function.py
textattack/goal_functions/text/minimize_bleu.py
textattack/goal_functions/text/non_overlapping_output.py
textattack/shared/attack.py

Clear caches of various components after a single attack to reduce memory usage.

add cache clearing

---

Makefile
textattack/attack_recipes/pwws_ren_2019.py
textattack/search_methods/greedy_word_swap_wir.py

Just a little cleanup:
- Moving the calculation of `index_order` to its own function
- Changing around a few variable names
- Removing some extra blank lines.

Clean up greedy-wir

---

requirements.txt
tests/test_command_line/test_augment.py
textattack/datasets/huggingface_nlp_dataset.py
textattack/transformations/word_swap_masked_lm.py

fix nlp dependency since it's taking them awhile to update their pypi :-)

update nlp dependency

---

textattack/commands/attack/run_attack_parallel.py

We need to reseed in every parallel workers to have reproducible attacks.

Add reseeding for parallel workers

---

textattack/shared/attacked_text.py

fix single-word attack bug

---

tests/sample_outputs/list_augmentation_recipes.txt
textattack/augmentation/__init__.py
textattack/augmentation/augmenter.py
textattack/augmentation/recipes.py
textattack/commands/augment.py

This augmentation recipe uses INV testing transformations implemented in the CheckList attack recipe

CheckList-Inv augmentation

---

requirements.txt
tests/sample_outputs/run_attack_stanza_pos_tagger.txt
tests/test_command_line/test_attack.py
textattack/constraints/grammaticality/part_of_speech.py
textattack/shared/utils/install.py
textattack/shared/utils/strings.py

* Added Stanza support for the `PartOfSpeech` constraint
* Added test for using Stanza as the part of speech tagger

Add stanza support for part-of-speech constraint

---

README.md

One of our users asked in the question panel about how to create his own augmenter in python. This is actually very useful and pretty easy to do with just a few lines of code.

Update README -- how to customize augmenter

---

textattack/search_methods/particle_swarm_optimization.py

This PR fixes issue #307, where using PSO search algorithm with query budget results in an error.

fix pso to work with budget query

---

README.md

There's a typo I made with the augmenter example.
Also we now have five augmentation recipes instead of three!

Fix ReadMe Minor Mistakes

---

docs/1start/references.md

update the textAttack paper abstract to the most-recent-version

update the textAttack paper abstract to the most-recent-version

---

docs/2notebook/3_Augmentations.ipynb
docs/index.rst

Notebook that introduces new users to TextAttack augmentation!

Add Augmentation Notebook

---

tests/sample_outputs/run_attack_stanza_pos_tagger.txt
tests/test_command_line/test_attack.py
textattack/shared/utils/install.py

Update expected output for one of the tests to resolve test failure reported in master and other branches. The discrepancy was caused by an update with  the stanza's English resource. 
- `tests/sample_outputs/run_attack_stanza_pos_tagger.txt`: Update the test with new output.
- Increment `post_install_check_2` to `post_install_check_3` to cause re-installation of stanza resources. 
- [  x] The title of your pull request should be a summary of its contribution.
- [  x] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  x] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the …

update test output to ignore num_queries

---

textattack/datasets/dataset.py

- in datasets/dataset.py, added output scale factor assignment

add output scale factor assignment

---

requirements.txt

*PyTorch's latest release (1.8) breaks LSTM models trained on version 1.7 and older. This PR fixes Torch version to 1.7.1 which is the last version which did not break LSTM models*
- *None*
- *Changed torch to torch==1.7.1*
- *None*
- [ x ] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the issue know you   are working on it)
- [ x ] To indicate a work in progress please mark it as a draft on Github.
- [ x ] Make sure existing tests pass.
- …

Fix torch version to 1.7.1

---

tests/test_command_line/test_attack.py
textattack/commands/attack/attack_args_helpers.py
textattack/datasets/huggingface_dataset.py

Revert "add --split to specify train/test/dev dataset"

---

Makefile
docs/1start/installation.rst

- This PR adds additional installation documentation for installing CUDA alongside TextAttack.
- Under "Get Started/Installation" on the documentation, I added three methods to install and use CUDA with TextAttack.
- Changed the Makefile for `docs-auto` because `sphinx-autobuild` updated and changed its CLI.
- None

CUDA installation documentation

---

docs/1start/talks-visualization.md
docs/index.rst

*This PR adds one more document page in readthedoc*
- [x ] The title of your pull request should be a summary of its contribution.
- [x ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  ] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify …

add in talks-visualization.md for our tutorial talks on TextAttack

---

docs/1start/benchmark-search.md

Fix multiple small errors in the document files 
- [  ] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify …

fix minor documentation errors 

---

docs/2notebook/Example_1_sklearn.ipynb

Made the necessary changes to enable it to work with the new API
Updated Notebook 5 scikit-learn example to work with the new API for textattack
- reduced the number of features in the transform_BOW() and transform_tfidf() to 100 to make the model computationally lighter (and have it actually run on Google Colab)
- updated the last cell to use the Attacker class and run the adversarial attack
- [ * ] The title of your pull request should be a summary of its contribution.
- [ * ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [ * ] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people …

Update Example_1_sklearn.ipynb for the api-rework branch

---

docs/2notebook/1_Introduction_and_Transformations.ipynb

Fixed Tutorial 1 Notebook
- [ x ] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the issue know you   are working on it)
- [ x ] To indicate a work in progress please mark it as a draft on Github.
- [ x ] Make sure existing tests pass.
- [ x ] Add relevant tests. No quality testing = no merge.
- [ x ] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify the appropriate …

Fixed Notebook Tutorial 1

---

docs/2notebook/Example_6_Keras.ipynb

Fixes Keras Notebook Tutorial for api-rework branch.

Keras Fix for api rework

---

docs/1start/what_is_an_adversarial_attack.md
tests/test_command_line/test_attack.py
textattack/commands/attack/attack_args.py

Rename all instances of faster-alzantot to fast-alzantot

---

textattack/commands/train_model/run_training.py

Run training bug

---

textattack/transformations/word_swaps/word_swap_qwerty.py

return [] when not in adj list

---

textattack/commands/attack/attack_args_helpers.py
textattack/commands/peek_dataset.py

*Example: This PR provides a solution to Issue #447*

Proposed solution to Issue #447

---

docs/0_get_started/command_line_usage.md
docs/3recipes/attack_recipes_cmd.md
docs/3recipes/augmenter_recipes_cmd.md

Update documentation /recipes folder with two new markdown files that explain how to run recipes  (attack recipes and augmenter recipes) from the command lines. 
- *Example: Added `clare` recipe as `textattack.attack_recipes.CLARE2020`.*
- [x ] Make sure existing tests pass.

add two recipes_cmd.md files

---

README.md
docs/1start/FAQ.md
requirements.txt

This is in response to https://github.com/QData/TextAttack/issues/489 
- seems scipy==1.4.1 unnecessary 
- scipy>=1.4.1 
- two minor documentation updates adding how to install from master version via 
```bash
git clone https://github.com/QData/TextAttack.git
cd TextAttack
pip install .[dev]
```
- [x ] The title of your pull request should be a summary of its contribution.
- [x ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [ x] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the issue know you   are working on it)
- [  ] To indicate a work in progress please mark it as …

scipy version plus minor documentation updates

---

tests/test_augment_api.py
textattack/constraints/semantics/word_embedding_distance.py

*add more tests for augment testing functions*
* the tests are based on PR: https://github.com/QData/TextAttack/pull/368 
- [  ] All public methods must have informative docstrings …

add more tests for augment function

---

.gitignore
README.md
README_ZH.md
docs/0_get_started/command_line_usage.md
docs/1start/attacks4Components.md
docs/1start/multilingual-visualization.md
docs/3recipes/attack_recipes_cmd.md
docs/3recipes/augmenter_recipes_cmd.md
examples/attack/attack_camembert.py
examples/attack/attack_from_components.sh
examples/augmentation/augment.csv
examples/augmentation/augment.sh
examples/augmentation/example.csv
examples/train/train_lstm_imdb_sentiment_classification.sh
examples/train/train_lstm_rotten_tomatoes_sentiment_classification.sh
textattack/training_args.py

* Fixing bugs in those examples codes under /example folder*
- Updating documentation to make the extended functions like multilingual supports easier to find
- Updating the augment example code to reflect the CLI augment argument name changes 
- correct the bugs in examples/attack/attack_camembert.py
- Remove unnecessary files under examples/augment/
- [  ] All public methods must have informative docstrings that work …

bug fix for codes in example folder

---

README.md
docs/1start/FAQ.md
examples/attack/attack_keras_parallel.py

Issue #499 highlighted serious problems when running attacks on Keras models in parallel
This PR adds a new script in `examples/attack/` for attacking TF2.5+ Keras versions in parallel.
- *New script in `examples/attack/`*
- None
- None
- [ x ] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the issue know you   are working on it)
- [ x ] To indicate a work in progress please mark it as a draft on Github.
- [ x ] Make sure existing tests …

[CODE] Keras parallel attack fix - Issue #499

---

docs/1start/A2TforVanillaAT.md
docs/3recipes/attack_recipes.rst
docs/index.rst
textattack/attack_recipes/pruthi_2019.py

We add the A2T attack recipe details into the docs 

update recipe docs with A2T new recipe

---

textattack/attack.py

Fix a minor typo

---

docs/2notebook/3_Augmentations.ipynb

Added instructions on using high-yield and enable-advance-metrics to the augmentation notebook

Update Augmentation Notebook

---

textattack/transformations/word_swaps/word_swap_change_location.py
textattack/transformations/word_swaps/word_swap_change_name.py
textattack/transformations/word_swaps/word_swap_change_number.py
textattack/transformations/word_swaps/word_swap_contract.py
textattack/transformations/word_swaps/word_swap_embedding.py
textattack/transformations/word_swaps/word_swap_extend.py
textattack/transformations/word_swaps/word_swap_gradient_based.py
textattack/transformations/word_swaps/word_swap_homoglyph_swap.py
textattack/transformations/word_swaps/word_swap_hownet.py
textattack/transformations/word_swaps/word_swap_neighboring_character_swap.py
textattack/transformations/word_swaps/word_swap_qwerty.py
textattack/transformations/word_swaps/word_swap_random_character_deletion.py
textattack/transformations/word_swaps/word_swap_random_character_insertion.py
textattack/transformations/word_swaps/word_swap_random_character_substitution.py
textattack/transformations/word_swaps/word_swap_wordnet.py

Add docstrings for transformation with API usage, transformation classes are showcased using augmenters since it is the most direct way users can visualize the transformations taking place.

Update Transformation Docstrings with API usage

---

docs/0_get_started/installation.md
textattack/attack_recipes/bert_attack_li_2020.py

- Change installation document using textattack[tensorflow] as default guidance. 
- [X ] The title of your pull request should be a summary of its contribution.
- [X ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  ] All public methods must have informative docstrings that work nicely with sphinx. For new …

change the default installation documentation to textattack[tensorflow]

---

docs/requirements.txt

- doc github compile gets format errors
- Seems caused by library dependency issues.. but everything runs fine locally and on read-the-doc
- [x  ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  ] All public methods must have …

Update requirements.txt for doc compilation format warnings

---

.github/workflows/check-formatting.yml
CONTRIBUTING.md
docs/conf.py
tests/test_attacked_text.py
tests/test_word_embedding.py
textattack/attack.py
textattack/attack_args.py
textattack/constraints/grammaticality/cola.py
textattack/constraints/grammaticality/language_models/google_language_model/alzantot_goog_lm.py
textattack/constraints/grammaticality/part_of_speech.py
textattack/constraints/pre_transformation/__init__.py
textattack/constraints/pre_transformation/max_num_words_modified.py
textattack/constraints/semantics/sentence_encoders/thought_vector.py
textattack/constraints/semantics/sentence_encoders/universal_sentence_encoder/universal_sentence_encoder.py
textattack/goal_functions/goal_function.py
textattack/goal_functions/text/minimize_bleu.py
textattack/goal_functions/text/non_overlapping_output.py
textattack/metrics/attack_metrics/words_perturbed.py
textattack/search_methods/greedy_word_swap_wir.py
textattack/shared/attacked_text.py
textattack/shared/utils/misc.py
textattack/shared/utils/strings.py

- Ability to specify device via `TA_DEVICE` env variable
- New constraint, `MaxNumWordsModified`
- Tracks previous AttackedText during attack to allow for reconstruction of chain of modifications
- Change`GreedyWordSwapWIR` to allow passing of specific unk token
- Format stuff
- Bump version to 0.3.5
- Downgrade USE from version 4 to 3 so that it works now (closes #640)
- Update FLAIR usage for new API (closes #638, #642)
- Formats things

Bug fixes and tweaks

---

tests/test_command_line/test_attack.py
tests/test_command_line/test_train.py

This PR commented out two slow tests: 
- 1. run_attack_faster_alzantot_recipe
- 2. test_train_tiny
- [x ] The title of your pull request should be a summary of its contribution.
- [ X] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  ] All public methods must have informative docstrings that work nicely with …

comment out the slow tests

---

textattack/datasets/huggingface_dataset.py

*`HuggingFaceDataset` class has a list of common schemas to find the input and output columns. 
Current list of schemas does not have SQUAD schema leading to ValueError.*
*Commit adds SQUAD schema to common schemas list in`get_datasets_dataset_columns`.*
- *Added traditionally used SQUAD schema to `get_datasets_dataset_columns` in `HuggingFaceDataset.py`.*
Fixes #597 

Add SQUAD schema to HuggingFaceDataset class

---

textattack/trainer.py

*In `trainer.py` `total_training_steps` are calculated for determining the optimzer scheduler steps.*
*Current calculation does not take into consideration that `num_train_adv_examples` can be either float , integer and also -1.
Adversarial example generation also did not take into the consideration when the value of num_train_adv_examples is -1.*
*PR includes adversarial example generation when `num_train_adv_examples` is -1 and includes right calculation steps
for the scheduler for the optimizer.*
- *Added code into ` _generate_adversarial_examples` to handle when  num_train_adv_examples is -1 which means we need get all possible adversarial text examples.*
- *Added code suggested by @d223302 for calculation of `total_adv_training_steps` based on num_train_adv_examples  datatype.*
Fixes …

Fix total_adv_training_steps calculation in trainer.py

---

textattack/models/wrappers/huggingface_model_wrapper.py
textattack/training_args.py

*PR adds T5 model classes to assert statements in HuggingFaceModelWrapper class and adds assertion checks to determine model and dataset compatibility in training_args to avoid `RuntimeError: CUDA error: device-side assert triggered` *
- *Added `T5ForTextToText` Class  and `T5Tokenizer` Class  to existing assert statements in  `HuggingFaceModelWrapper` Class.*
- *Added checks to compare dataset labels and model outputs.*
- *Added checks to make sure labels do not have negative values which PyTorch does not support.*
Fixes #488 

Fix training issues 488

---

textattack/goal_function_results/classification_goal_function_result.py
textattack/goal_function_results/goal_function_result.py
textattack/goal_function_results/text_to_text_goal_function_result.py

*Adds __repr__  to GoalFunctionResult  and AttackResult *
- *__repr__ function for GoalFunctionResult.*
Example of __repr__ for `GoalFunctionResult`
```
GoalFunctionResult( 
(goal_function_result_type): Classification
(attacked_text): The sailors rode the breeze cleEar of the rocks.
(ground_truth_output): 1
(model_output): 0
(score): 0.8867838978767395
```
Closes #242

Add __repr__ for GoalFunctionResult Class

---

.github/workflows/run-pytest.yml
setup.py

*Tensorflow `2.7.0` has more relaxed numpy restrictions which allows for fixing #670*

Update Tensorflow Version to `2.7.0`

---

textattack/datasets/helpers/ted_multi.py
textattack/shared/attacked_text.py
textattack/shared/utils/strings.py

Fixes slow AttackedText comparisons, issues with splitting Chinese text when calling `words_from_text`, and #697.

fix bugs in AT, strings (Chinese), TedMulti dataset

---

textattack/commands/textattack_cli.py

`'texattack'` -> `'textattack'`

fix command help str :-)

---

docs/3recipes/attack_recipes_cmd.md

This PR fixes the links and slightly cleans up the formatting on the page [Four Components of TextAttack Attacks](https://textattack.readthedocs.io/en/latest/1start/attacks4Components.html). 
None
- Links now work on the above mentioned page
- Added author and publish date to one paper

Clean up formatting in HTML tables

---

docs/1start/multilingual-visualization.md
docs/1start/references.md
docs/index.rst

Adding notebook tutorial for Chinese TextAttack 
- [ x] The title of your pull request should be a summary of its contribution.
- [ x] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  ] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify the …

add in tutorials and reference for Chinese Textattack

---

textattack/attack.py

*This PR fixes several issues in the example of an Attack API. Without the fixes, a user is not able to run the example code*
- *I added several package imports such as _WordSwapEmbedding_, GreedyWordSwapWIR as the example shows **package not found** issue. *
- *I updated the call of Attack API in line 73*

Fixed syntax and import issues in the example of Attack API

---

docs/conf.py

move to 0.3.10
*Example: This PR adds [CLARE](https://arxiv.org/abs/2009.07502) attack, which uses distilled RoBERTa masked language model to perform word swaps, word insertions, word merges (which is where we combine two adjacent words and replace it with another word) in a greedy manner.  s*
- *Example: Added `clare` recipe as `textattack.attack_recipes.CLARE2020`.*
- *Example: `WordSwapMaskedLM` has been updated to have a minimum confidence score cutoff and batching has been added for faster performance.*
- *Example: Remove unnecessary files under `textattack.models...`*
- [  ] The title of your pull request should be a summary of its contribution.
- [  ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why …

Update conf.py ..a new release 0.3.10
